version: "3.2"
services:
  mysql:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=comics
      - MYSQL_USER=django_admin
      - MYSQL_PASSWORD=testpass
    ports:
      - "3306:3306"
  app:
    build: .
    command: bash -c "while ! nc -w 1 -z mysql 3306; do sleep 0.1; done; ./manage.py migrate; ./manage.py scrape_for_new_comics; while :; do ./manage.py runserver 0.0.0.0:8000; sleep 1; done" 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
