version: "3.2"
services:
  mysql:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=comics
      - MYSQL_USER=django_admin
      - MYSQL_PASSWORD=testpass
    ports:
      - "3306:3306"
  app:
    build: .
    expose:
      - 8000
    depends_on:
      - mysql
    environment:
      IN_DOCKER: 1
  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - app
