# Generated by Django 2.1.5 on 2020-06-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20200607_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={},
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='species',
            name='water_frequency',
        ),
        migrations.AddField(
            model_name='species',
            name='days_between_watering_max',
            field=models.SmallIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='days_between_watering_min',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
