# Generated by Django 2.1.5 on 2020-06-13 17:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20200610_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watering',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='watering',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watered', to='plants.Plant'),
        ),
        migrations.AlterUniqueTogether(
            name='watering',
            unique_together={('plant', 'date')},
        ),
    ]
