# Generated by Django 2.1.5 on 2020-06-15 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20200613_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watering',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
