# Generated by Django 2.1.5 on 2020-06-17 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_auto_20200615_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spot', to='plants.Spot'),
        ),
        migrations.AlterField(
            model_name='species',
            name='lighting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lighting', to='plants.Lighting'),
        ),
    ]
