# Generated by Django 2.1.5 on 2020-06-28 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20200617_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watering',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
