# Generated by Django 2.1.5 on 2020-08-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20200628_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['display_name', 'species__name']},
        ),
        migrations.RemoveField(
            model_name='plant',
            name='purchase_date',
        ),
    ]
