# Generated by Django 2.1.5 on 2020-08-30 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_create_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='spots', to='plants.Room'),
            preserve_default=False,
        ),
    ]
